global:
  scrape_interval: 5s

scrape_configs:
  # Scrape the metrics from our custom Java Application
  - job_name: 'java-samiti-app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8083']
      
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
